config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'

  resources :roles
  resources :features

  resources :actions
  resources :roleauthtemplates
  resources :userauthmap
  post "userauthmap/:id" => "userauthmap#update"	

end

app/models/role_auth_template.rb
class RoleAuthTemplate < ActiveRecord::Base
  self.table_name = "tpl_role_auth_map"
  has_one :role, foreign_key: "role_id"
end

app/controllers/roleauthtemplates_controller.rb
class RoleauthtemplatesController < ApplicationController
  # Routes:
  #     roleauthtemplates GET    /roleauthtemplates(.:format)          roleauthtemplates#index
  #                       POST   /roleauthtemplates(.:format)          roleauthtemplates#create
  #  new_roleauthtemplate GET    /roleauthtemplates/new(.:format)      roleauthtemplates#new
  # edit_roleauthtemplate GET    /roleauthtemplates/:id/edit(.:format) roleauthtemplates#edit
  #      roleauthtemplate GET    /roleauthtemplates/:id(.:format)      roleauthtemplates#show
  #                       PATCH  /roleauthtemplates/:id(.:format)      roleauthtemplates#update
  #                       PUT    /roleauthtemplates/:id(.:format)      roleauthtemplates#update
  #                       DELETE /roleauthtemplates/:id(.:format)      roleauthtemplates#destroy

  def index
    getActionCode

	# display list of all roles in system
    @roles = Role.all
  end

  def show
	getActionCode
    puts ("take a break")

	# display list of all auths for the given role

	@roleTemplates = RoleAuthTemplate.where("role_id = :role_id", { :role_id => params[:id] }).all
	
	# for debugging only
	# render json: @roleTemplates.to_json
	# render plain: @roleTemplates.inspect
  end

  def new
    getActionCode
  end

  def edit
    getActionCode
  end

  def create
    getActionCode
  end

  def update
    getActionCode
  end

  def destroy
    getActionCode
  end
end

app/views/roleauthtemplates/index.html.erb
<h1>Role Authorizations Templates</h1>

<h2>Select Role to view authorizations</h2>

<table>
  <tr>
	<th>role_id</td>
	<th>role_name</td>
	<th>role_desc</td>
	<th>status</td>
    <th>See</th>
    <th>Edit</th>
  </tr>
 
  <% @roles.each do |vRole| %>
    <tr>
      <td><%= vRole.role_id %></td>
      <td><%= vRole.role_name %></td>
      <td><%= vRole.role_desc %></td>
      <td><%= vRole.status %></td>
      
	  <td><%= link_to 'Show', roleauthtemplate_path(vRole) %></td>

      <td><%= link_to 'Edit', edit_roleauthtemplate_path(vRole) %></td>
	  
    </tr>
  <% end %>
</table>

app/views/roleauthtemplates/show.html.erb
<h1>Role Authorizations</h1>

<%= link_to 'Back to Role list', roleauthtemplates_path %>
<hr/>

<table>
  <tr>
	<th>role_id</th>
	<th>action_id</th>
	<th>feature_id</th>
	<th>action_name</th>
	<th>status</th>
	<th>add_by</th>
	<th>add_on</th>
	<th>edit_by</th>
	<th>edit_on</th>
  </tr>
 
  <% @roleTemplates.each do |vRT| %>
    <tr>
      <td><%= vRT.role_id %></td>
      <td><%= vRT.action_id %></td>
      <td><%= vRT.feature_id %></td>
      <td><%= vRT.action_name %></td>
      <td><%= vRT.status %></td>
      <td><%= vRT.add_by %></td>
      <td><%= vRT.add_on.strftime("%Y-%m-%d %H:%M:%S") %></td>
      <td><%= vRT.edit_by %></td>
      <td><%= vRT.edit_on.strftime("%Y-%m-%d %H:%M:%S") %></td>
    </tr>
  <% end %>
</table>

<hr/>
<%= link_to 'Back to Role list', roleauthtemplates_path %>