config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'

  resources :roles
  resources :features

  resources :actions
  resources :roleauthtemplates
  resources :userauthmap
  post "userauthmap/:id" => "userauthmap#update"	

end

app/models/role.rb
class Role < ActiveRecord::Base
	self.table_name = "gen_roles"
	self.primary_key = "role_id"

	# link to 'user_role_map'
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  require "securerandom"
  # Routes:
  #     roles GET    /roles(.:format)          roles#index
  #           POST   /roles(.:format)          roles#create
  #  new_role GET    /roles/new(.:format)      roles#new
  # edit_role GET    /roles/:id/edit(.:format) roles#edit
  #      role GET    /roles/:id(.:format)      roles#show
  #           PATCH  /roles/:id(.:format)      roles#update
  #           PUT    /roles/:id(.:format)      roles#update
  #           DELETE /roles/:id(.:format)      roles#destroy
  #
  # A frequent practice is to place the standard CRUD actions in each controller
  # in the following order:
  #    - index
  #    - show
  #    - new
  #    - edit
  #    - create
  #    - update
  #    - destroy

  include RolesHelper

  def index
	getActionCode
	# puts "#{getActionCode()} << Called from RolesController.index"

	# @lsTag = SecureRandom.hex(24)
	# puts "Using tag => #{@lsTag}"

	# puts testMethodOuter
	# @MyHelper = RoleHelperOne.new
	# puts @MyHelper.testMethodInner

	# puts "Testing Inheritance ..."
	# testPrivate
	# testProtected
	puts ("take a break")

    @roles = Role.all
  end

  def show
	puts getActionCode
	
    # render plain: params[:id].inspect
    # render plain: params[:role].inspect
    @role = Role.find(params[:id])
  end

  def new
    getActionCode
    @role = Role.new
  end

  def edit
    getActionCode
    @role = Role.find(params[:id])
  end

  def create
    puts "In RolesController => create"
    getActionCode
    # render plain: params[:role].inspect

    @role = Role.new(role_params)

    # The render method is used so that the @article object
    # is passed back to the new template when it is rendered.
    # This rendering is done within same request as the form submission
    # whereas the redirect_to will tell browser to issue another request.
    if @role.save
      redirect_to @role
    else
      render "new"
    end
  end

  def update
    getActionCode
    @role = Role.find(params[:id])
  end

  private

  def role_params
    params.require(:role).permit(:role_id, :role_name, :role_desc, :status)
  end

end

app/helpers/roles_helper.rb
module RolesHelper

def testMethodOuter
    @htagO = "RolesHelper.testMethodOuter <== CALLED"
  end

  class RoleHelperOne
		def testMethodInner
			@htagI = "RolesHelper.RoleHelperOne.testMethodInner <== CALLED"
		end
	end
	
end

app/views/roles/edit.html.erb
<p><strong>role_id:</strong><%= @role.role_id %></p>
<p><strong>role_name:</strong><%= @role.role_name %></p>
<p><strong>role_desc:</strong><%= @role.role_desc %></p>
<p><strong>status:</strong><%= @role.status %></p>
<p><strong>add_by:</strong><%= @role.add_by %></p>
<p><strong>add_on:</strong><%= @role.add_on %></p>
<p><strong>edit_by:</strong><%= @role.edit_by %></p>
<p><strong>edit_on:</strong><%= @role.edit_on %></p>


<hr/>
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<h1>Listing Roles</h1>
 
<pre><%= @lsTag %></pre>

<%= link_to 'Create New Role', new_role_path %>

<table>
  <tr>
	<th>role_id</td>
	<th>role_name</td>
	<th>role_desc</td>
	<th>status</td>
	<th>add_by</td>
	<th>add_on</td>
	<th>edit_by</td>
	<th>edit_on</td>
    <th></th>
    <th></th>
  </tr>
 
  <% @roles.each do |vRole| %>
    <tr>
      <td><%= vRole.role_id %></td>
      <td><%= vRole.role_name %></td>
      <td><%= vRole.role_desc %></td>
      <td><%= vRole.status %></td>
      <td><%= vRole.add_by %></td>
      <td><%= vRole.add_on %></td>
      <td><%= vRole.edit_by %></td>
      <td><%= vRole.edit_on %></td>
      <td><%= link_to 'Show', role_path(vRole) %></td>
      <td><%= link_to 'Edit', edit_role_path(vRole) %></td>
	  
    </tr>
  <% end %>
</table>

app/views/roles/new.html.erb
<!--
Refer: https://guides.rubyonrails.org/form_helpers.html
see 2.2
:role_id, :role_name, :role_desc, :status


-->
<h1>New Role</h1>
<%= form_for :role, url: roles_path do |f| %>

  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@role.errors.count, "error") %> prohibited
        this role from being saved:
      </h2>
      <ul>
        <% @role.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


	<div>
		<%= f.label :role_name %>
		<%= f.text_field :role_name %>
	</div>

	<div>
		<%= f.label :role_desc %>
		<%= f.text_field :role_desc %>
	</div>

	<div>
		<%= f.label :status %>
		<%= f.text_field :status %>
	</div>

  	<%= f.submit "Create" %>

<% end %>



<hr/>
<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p><strong>role_id:</strong><%= @role.role_id %></p>
<p><strong>role_name:</strong><%= @role.role_name %></p>
<p><strong>role_desc:</strong><%= @role.role_desc %></p>
<p><strong>status:</strong><%= @role.status %></p>
<p><strong>add_by:</strong><%= @role.add_by %></p>
<p><strong>add_on:</strong><%= @role.add_on.strftime("%Y-%m-%d %H:%M:%S") %></p>
<p><strong>edit_by:</strong><%= @role.edit_by %></p>
<p><strong>edit_on:</strong><%= @role.edit_on.strftime("%Y-%m-%d %H:%M:%S") %></p>
<p><strong>Current Time:</strong><%= Time.now.strftime("%Y-%m-%d %H:%M:%S") %></p>


<hr/>
<%= link_to 'Back', roles_path %>