config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'

  resources :roles
  resources :features

  resources :actions
  resources :roleauthtemplates
  resources :userauthmap
  post "userauthmap/:id" => "userauthmap#update"	

end

app/models/feature.rb
class Feature < ActiveRecord::Base
	self.table_name = "gen_features"
	self.primary_key = "feature_id"

	has_many :actions, foreign_key: "feature_id"
	# has_many: :user_auth_maps, :through actions, foreign_key: "feature_id"
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  include SelectOptionsHelper
  # Routes:
  #      features GET    /features(.:format)          features#index
  #               POST   /features(.:format)          features#create
  #   new_feature GET    /features/new(.:format)      features#new
  #  edit_feature GET    /features/:id/edit(.:format) features#edit
  #       feature GET    /features/:id(.:format)      features#show
  #               PATCH  /features/:id(.:format)      features#update
  #               PUT    /features/:id(.:format)      features#update
  #               DELETE /features/:id(.:format)      features#destroy

  def index
    getActionCode
    @features = Feature.includes(:actions).all
	# puts ("take a break")
	# render json: @features.to_json(root: true, include: :actions)
  end

  def show
    getActionCode
    # render plain: params[:action].inspect
    @feature = Feature.find(params[:id])
  end

  def new
    getActionCode
    @feature = Feature.new
  end

  def edit
    getActionCode
	# render plain: params[:action].inspect
	@StatusArray = statusOptions
    @feature = Feature.find(params[:id])
    # puts @feature
  end

  def create
    puts "In RolesController => create"
    getActionCode
    # render plain: params[:role].inspect

    @feature = Feature.new(action_params)

    # The render method is used so that the @article object
    # is passed back to the new template when it is rendered.
    # This rendering is done within same request as the form submission
    # whereas the redirect_to will tell browser to issue another request.
    if @Feature.save
      redirect_to @feature
    else
      render "new"
    end
  end

  def update
	getActionCode
	@NewStatus = params[:status]
    @feature = Feature.find(params[:id])
    if @feature.update_attributes(feature_params)
      redirect_to :action => "show", :id => @feature
    else
      puts "Error saving"
      # Show the error message
    end
  end

  private

  def feature_params
    params.require(:feature).permit(:feature_id, :feature_code, :feature_name, :feature_desc, :status)
  end

end

app/views/features/edit.html.erb
<%= form_for @feature, :url => { :action => "update" } do |vA| %>
	<p>Form will come here</p>
  <% if @feature.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@feature.errors.count, "error") %> prohibited
        this role from being saved:
      </h2>
      <ul>
        <% @feature.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

	<div>
		<%= vA.label :feature_code %>
		<%= vA.text_field :feature_code %>
	</div>

	<div>
		<%= vA.label :feature_name %>
		<%= vA.text_field :feature_name %>
	</div>

	<div>
		<%= vA.label :feature_desc %>
		<%= vA.text_field :feature_desc %>
	</div>

	<div>
		<%= vA.label :status %>
		<%= vA.select(:status,@StatusArray) %>

	</div>

	<div> Last updated on  <%= @feature.edit_on.strftime("%Y-%m-%d %H:%M:%S") %> 	</div>
	<div> Current Time is  <%= Time.now.strftime("%Y-%m-%d %H:%M:%S") %> 	</div>
	

	<%= 
	button_tag(type: 'submit') do
		  content_tag(:strong, 'Save me!')
		end
	%>


<% end %>


<hr/>
<%= link_to 'Back', features_path %>

app/views/features/index.html.erb
<h1>Listing Features</h1>
 
<%= link_to 'Create New Feature', new_role_path %>

<table>
  <tr>
	<th>feature_id</td>
	<th>feature_code</td>
	<th>feature_name</td>
	<th>feature_desc</td>
	<th>status</td>
	<th>Last edit</td>
    <th></th>
    <th></th>
  </tr>
 
  <% @features.each do |vFeature| %>
    <tr>
      <td><%= vFeature.feature_id %></td>
      <td><%= vFeature.feature_code %></td>
      <td><%= vFeature.feature_name %></td>
      <td><%= vFeature.feature_desc %></td>
      <td><%= vFeature.status %></td>
      <td><%= vFeature.edit_on.strftime("%Y-%m-%d %H:%M:%S") %></td>
      <td><%= link_to 'Show', feature_path(vFeature) %></td>
      <td><%= link_to 'Edit', edit_feature_path(vFeature) %></td>
    </tr>
  <% end %>
</table>

app/views/features/show.html.erb
<p><strong>feature_id:</strong><%= @feature.feature_id %></p>
<p><strong>feature_code:</strong><%= @feature.feature_code %></p>
<p><strong>feature_name:</strong><%= @feature.feature_name %></p>
<p><strong>feature_desc:</strong><%= @feature.feature_desc %></p>
<p><strong>status:</strong><%= @feature.status %></p>
<p><strong>add_by:</strong><%= @feature.add_by %></p>
<p><strong>add_on:</strong><%= @feature.add_on.strftime("%Y-%m-%d %H:%M:%S") %></p>
<p><strong>edit_by:</strong><%= @feature.edit_by %></p>
<p><strong>edit_on:</strong><%= @feature.edit_on.strftime("%Y-%m-%d %H:%M:%S") %></p>
<p><strong>Current Time:</strong><%= Time.now.strftime("%Y-%m-%d %H:%M:%S") %></p>

<hr/>
<%= link_to 'Back', features_path %>